---

version: "0.0"
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "{{task_definition}}"
        LoadBalancerInfo:
          TargetGroupPairInfoList:
            - TargetGroupPairInfo:
                TargetGroups:
                  - Name: "{{backend_blue_target_group_name}}"
                  - Name: "{{backend_green_target_group_name}}"
                ProdTrafficRoute:
                  ListenerArns:
                    - "{{alb_listener_arn}}"